apiVersion: pkg.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: nutanix-provider-config
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: nutanix-creds
      key: credentials
---
apiVersion: v1
kind: Secret
metadata:
  name: nutanix-creds
  namespace: crossplane-system
type: Opaque
data:
  # Base64 encoded credentials in JSON format:
  # {
  #   "endpoint": "https://prism-central.example.com:9440",
  #   "username": "admin",
  #   "password": "your-password"
  # }
  credentials: eyJlbmRwb2ludCI6Imh0dHBzOi8vcHJpc20tY2VudHJhbC5leGFtcGxlLmNvbTo5NDQwIiwidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoieW91ci1wYXNzd29yZCJ9
