apiVersion: meta.pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-nutanix
  annotations:
    meta.crossplane.io/maintainer: Mohan George <your@email.com>
    meta.crossplane.io/source: github.com/mgeorge67701/crossplane-nutanix
    meta.crossplane.io/license: Apache-2.0
    friendly-name.meta.crossplane.io: Provider Nutanix
    meta.crossplane.io/description: |
      The Crossplane Nutanix provider enables management of Nutanix resources.
    meta.crossplane.io/readme: |
      `provider-nutanix` is a Crossplane Provider that enables deployment and management
      of Nutanix resources on clusters provisioned by Crossplane.
spec:
  controller:
    image: ghcr.io/mgeorge67701/provider-nutanix:VERSION_PLACEHOLDER
  crds:
    - file: nutanix.crossplane.io_providerconfigs.yaml
    - file: nutanix.crossplane.io_virtualmachines.yaml