apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: providerconfigs.nutanix.crossplane.io
spec:
  group: nutanix.crossplane.io
  names:
    kind: ProviderConfig
    listKind: ProviderConfigList
    plural: providerconfigs
    singular: providerconfig
  scope: Cluster
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                credentials:
                  type: object
                  properties:
                    source:
                      type: string
                    secretRef:
                      type: object
                      properties:
                        namespace:
                          type: string
                        name:
                          type: string
                        key:
                          type: string
