apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: virtualmachines.nutanix.crossplane.io
spec:
  group: nutanix.crossplane.io
  names:
    kind: VirtualMachine
    listKind: VirtualMachineList
    plural: virtualmachines
    singular: virtualmachine
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                numVcpus:
                  type: integer
                memorySizeMib:
                  type: integer
                clusterUuid:
                  type: string
                subnetUuid:
                  type: string
                imageUuid:
                  type: string
            status:
              type: object
              properties:
                vmId:
                  type: string
                state:
                  type: string
