apiVersion: meta.pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-nutanix
spec:
  controller:
    image: ghcr.io/mgeorge67701/provider-nutanix:latest
  description: Crossplane provider for Nutanix
  keywords:
    - crossplane
    - nutanix
  maintainers:
    - name: Mohan George
      email: mohan.george@example.com
  source: https://github.com/mgeorge67701/crossplane-nutanix
  version: VERSION_PLACEHOLDER
